version: '3'

services:
  ftpd_server:
    image: stilliard/pure-ftpd
    container_name: pure-ftpd
    env_file:
      - ./.env
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes: 
      - "./data:/home/user"
      - "./passwd:/etc/pure-ftpd/passwd"
    environment:
      PUBLICHOST:  '${PUBLICHOST}'
      FTP_USER_NAME:  '${FTP_USER_NAME}'
      FTP_USER_PASS:  '${FTP_USER_PASS}'
      FTP_USER_HOME:  /home/user

    restart: always  
